### ISSUE TITLE
Console warning when setting item rarity to blank

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#211]
When setting item rarity to blank in the dropdown, the following warning occurs
```
commons.js:7439 TypeError: Failed data migration for ConsumableData: Cannot read properties of null (reading 'toLowerCase')
    at physical-item.mjs:87:68
    at Array.find (<anonymous>)
    at #migrateRarity (physical-item.mjs:86:58)
    at PhysicalItemTemplate._migrateData (physical-item.mjs:60:40)
    at ConsumableData._migrateData (abstract.mjs:231:16)
    at ConsumableData.migrateData (abstract.mjs:218:10)
    at ConsumableData.migrateDataSafe (commons.js:7436:14)
    at TypeDataField.migrateSource (commons.js:6743:22)
    at SchemaField.migrateSource (commons.js:5514:51)
    at Item5e.migrateData (commons.js:7423:19)
```

The issue is the Select component is intentionally setting things to null when the current target value is empty string. This was likely by design because of other issues related to null/undefined dropdown options.

First, determine if there would be any problems with simply allowing empty string in the Select `saveChanges` function. If there are issue, provide then appropriate prop(s) for opting into allowing empty string during save.

**Comment by kgar** [comment]
Closing as completed 💪
