### ISSUE TITLE
Delete Pact Magic Spell Error and Refresh issue

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#25]
https://discord.com/channels/732325252788387980/1116078321067892796/1170590609799655455

Loving the sheets so far! Ran into a bug when trying to delete a pact magic spell that prevented the sheet from refreshing to display that the spell was deleted. Re-opening the sheet showed it was removed successfully:

```
SpellbookItemCardContent.svelte:35 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toggleTitle')
    at Object.p (SpellbookItemCardContent.svelte:35:22)
    at Object.p (SpellbookItemCardContent.svelte:34:24)
    at Object.p (SpellbookItemCardContent.svelte:33:26)
    at Object.p (SpellbookItemCardContent.svelte:30:59)
    at update (scheduler.js:119:30)
    at flush (scheduler.js:79:5)
```

**Comment by kgar** [comment]
Resolved
