### ISSUE TITLE
Spell Atk Mod Label and Tooltip Disappear for Warlock

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#261]
When Midi-QoL + dependencies are turned on, and for a specific actor setup, the spell DC tooltip formatting throws an error because of expecting a string and getting a number. Ensure it accounts for this by normalizing the incoming data as a string.

## Reference

https://discord.com/channels/1167985253072257115/1197721154211811459

Heyo, after the latest update I've got an error whenever my warlocks character sheet is opened, and no spell attack bonus is displayed:

tidy5e-sheet-kgar | An error occurred while calculating spell attack bonus TypeError: formula.replace is not a function
    at Roll.validate (foundry.js:10597:23)
    at getDcTooltip (formula.ts:242:12)
    at calculateSpellAttackAndDc (formula.ts:134:18)
    at Tidy5eCharacterSheet.getData (Tidy5eCharacterSheet.ts:319:26)
    at async Tidy5eCharacterSheet._render (Tidy5eCharacterSheet.ts:451:18)

**Comment by kgar** [comment]
Closing as completed.
