### ISSUE TITLE
dnd5e 3.x Compatibility: Diagnose and Resolve Errors

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#350]
Diagnose the scale and scope of breakage and issues.
Fix small issues that are fixable right away.
For any missing features that can wait until after the rollout, log them and put them on the "3.x Feature Rollout" milestone.

### Ensure baseline functionality for all sheets

- [x] Character Sheet
    - [x] Header
    - [x] Attributes Tab
    - [x] Inventory Tab
    - [x] Spellbook Tab
    - [x] Features Tab
    - [x] Effects Tab
    - [x] Biography Tab
    - [x] Journal Tab
    - [x] Actions Tab
- [x] NPC Sheet
    - [x] Abilities Tab
    - [x] Spellbook Tab
    - [x] Features Tab
    - [x] Journal Tab
    - [x] Biography Tab
    - [x] Actions Tab
- [x] Vehicle Sheet
    - [x] Attributes Tab
    - [x] Cargo & Crew Tab
    - [x] Effects Tab
    - [x] Description Tab
    - [x] Actions Tab
- [x] Background Sheet
- [x] Class Sheet
- [x] Consumable Sheet
- [x] Container Sheet - #357
- [x] Equipment Sheet
- [x] Feature Sheet
- [x] Loot Sheet
- [x] Race Sheet
- [x] Spell Sheet
- [x] Subclass Sheet
- [x] Tool Sheet
- [x] Weapon Sheet

### Odds and Ends

- [x] Drag and drop ❗ (some issues already found)
    - [x] Character (Inventory, Spells, Spell Scrolls, Race, Class, Subclass, Feature)
    - [x] NPC (Inventory, Spells, Features, Actions, Attacks)
    - [x] Vehicle (Features/???, Spell Scrolls, Cargo)
- [x] Polymorphing
    - [x] Character
    - [x] NPC
    - [x] Vehicle
- [x] Interacting with Compendium Sheets vs. World Collection Sheets vs. Owned Sheets
    - [x] Actors
    - [x] Items

## Issues To Resolve Before Rollout

- [x] #351
```
VehicleCargoAndCrewTab.svelte:70 Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at saveSection (VehicleCargoAndCrewTab.svelte:70:18)
    at Array.func_1 (VehicleCargoAndCrewTab.svelte:205:29)
    at func_1 (VehicleCargoAndCrewTab.svelte:213:35)
    at HTMLInputElement.change_handler (TextInput.svelte:100:22)
```
- [x] #352
```
base-sheet.mjs:953 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'system')
    at ActorSheet._onDropSingleItem (base-sheet.mjs:953:21)
    at Tidy5eVehicleSheet._onDropSingleItem (Tidy5eKgarVehicleSheet.ts:332:31)
    at transformFirst (base-sheet.mjs:914:36)
    at createItemData (item.mjs:2421:66)
    at Item5e.createWithContents (item.mjs:2436:39)
    at Tidy5eVehicleSheet._onDropItemCreate (base-sheet.mjs:913:35)
    at Tidy5eVehicleSheet._onDropItem (base-sheet.mjs:874:17)
```
- [x] #353
When there is a description entered into the description tab, the next time the vehicle is opened, this error occurs:
```
logging.ts:37 tidy5e-sheet | Failed to render svelte tab TypeError: Cannot read properties of null (reading 'addEventListener')
    at Tidy5eVehicleSheet.activateListeners (vehicle-sheet.mjs:270:1)
    at Object.activateFoundryJQueryListeners (Tidy5eKgarVehicleSheet.ts:135:15)
    at activateProseMirrorListeners (VehicleDescriptionTab.svelte:12:14)
    at Object.mount [as m] (VehicleDescriptionTab.svelte:26:15)
    at Object.mount [as m] (RerenderAfterFormSubmission.svelte:2:30)
    at Object.mount [as m] (RerenderAfterFormSubmission.svelte:12:25)
    at mount (RerenderAfterFormSubmission.svelte:11:32)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=4c851f67:291:24)
    at mount_component (chunk-J2VQCU4O.js?v=4c851f67:2134:24)
    at Object.mount [as m] (VehicleDescriptionTab.svelte:28:7)
```
When saving changes to the description tab, this error occurs:
```
VehicleDescriptionTab.svelte:24 Uncaught (in promise) TypeError: dispose is not a function
    at Object.destroy [as d] (VehicleDescriptionTab.svelte:24:36)
    at Object.destroy [as d] (RerenderAfterFormSubmission.svelte:2:30)
    at Object.destroy [as d] (RerenderAfterFormSubmission.svelte:12:25)
    at chunk-J2VQCU4O.js?v=4c851f67:1408:17
    at run (chunk-J2VQCU4O.js?v=4c851f67:30:10)
    at Array.forEach (<anonymous>)
    at run_all (chunk-J2VQCU4O.js?v=4c851f67:36:7)
    at check_outros (chunk-J2VQCU4O.js?v=4c851f67:1389:5)
    at Object.update [as p] (RerenderAfterFormSubmission.svelte:11:32)
    at update (chunk-J2VQCU4O.js?v=4c851f67:1351:32)
```

## Can Wait Until Post Rollout
- Cleanup: Race, Background, Class, Subclass - Duplicate is not provided as an option on the legacy sheets
- Enhancement: Class Favorite is an option on the legacy sheet
- Style: Original Class marker missing from Tidy
- Migration/Enhancement: Biography fields are now official in the system: Faith, Gender, Eyes, Hair, Skin, Height, Weight, Age
    - Convert all Tidy flags to simply use the data that is there
    - Create a migration for all Character Sheets to migrate the biography flags to the new official schema. If possible allow for user to target only one actor or all actors (GM Only)
- Bug: When editing a contenteditable field, if the name field has a trailing space or if it has multiple spaces back-to-back, it converts spaces into `&nbsp;`, which is displayed on the Actors tab.
- Bug: NPCs' total count of prepared spells does not exist in their sheet context, so the Prepare Spells tracker is always 0.
- Style: Vehicle Dimensions dialog has unreadable text and stock Foundry styles. Ensure it's using the application shell for Tidy.
- Bug: Same with the Legacy vehicle sheet - Attempting to add "Equipment" produces this console error:
```
Tidy
commons.js:2572 Uncaught TypeError: Cannot create property 'value' on string 'equipment'
    at setProperty (commons.js:2572:19)
    at _expand (commons.js:2337:9)
    at Object.expandObject (commons.js:2341:12)
    at Object.createItem (foundry-adapter.ts:234:29)
    at HTMLButtonElement.defaultCreateFunction (ItemCreateButton.svelte:14:27)
    at HTMLButtonElement.<anonymous> (ItemCreateButton.svelte:21:19)

Legacy
commons.js:2572 Uncaught (in promise) TypeError: Cannot create property 'value' on string 'equipment'
    at setProperty (commons.js:2572:19)
    at _expand (commons.js:2337:9)
    at Object.expandObject (commons.js:2341:12)
    at InventoryElement._onCreate (inventory.mjs:402:29)
    at InventoryElement._onAction (inventory.mjs:352:21)
```
- Style: New dnd5e 3.x SVG icons are not fitting quite right in the Actions tab
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/5aeb471a-53d5-43e5-be55-15edfa788804)
- Style: New dnd5e 3.x SVG icons are not fitting quite right in the Background Advancement tab, Class Advancement tab, and Race Advancement tab
![image](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/assets/4632129/2c2d12fb-8e81-4487-86ff-45793e688d4b)

- #355 feat: (dnd5e 3.x) Item sheets - Obscure tab contents for unidentified items

## New Things to Think About After Stabilizing in 3.x

- Containers #357
- Ruletips, new tooltips, etc.
- Actor
    - Play Mode: Skills have a dropdown for which underlying ability applies to it
    - Conditions on the Effects Tab
    - Numerous biographical elements added
        - New fields: Eyes, Height, Faith, Hair, Weight, Gender, Skin, Age
    - Portrait/Token view toggle
    - Exhaustion automation baked into legacy / new / Tidy / whomever
    - Effects search
    - Spellbook: sort, filters, set primary spellcasting
- ...

**Comment by kgar** [comment]
PC Inventory
- Search :white_check_mark: 
- Filter :white_check_mark: 
- Expand All / Collapse All :white_check_mark: 
- List View :white_check_mark: 
- Grid View :white_check_mark: 
- Rolling / using items :white_check_mark: 
- Equip/Unequip :white_check_mark: 
- Toggle Favorite :white_check_mark: 
- Context Menu :white_check_mark: 
- Item Quantity change :white_check_mark: 
- Encumbrance :white_check_mark: 
- Edit/Duplicate/Delete :white_check_mark: 
- Sheet Lock :white_check_mark: 
- Attunement / Attunement Max Limit :white_check_mark: 
- ~~Currency Convert :x:~~ Manage Currency :white_check_mark:

~~Fixing currency conversion now. It should be an alternate function call, it looks like.~~ Done.

**Comment by kgar** [comment]
PC Spellbook
- Search :white_check_mark:
- Filter :white_check_mark: ~~:x: (filter won't open due to Localization error; most likely due to spell schools turning into objects instead of direct string mappings)~~
- Expand All / Collapse All :white_check_mark:
- List View :white_check_mark:
- Grid View :white_check_mark:
- Rolling / using spells :white_check_mark:
- Toggle Prepared :white_check_mark:
- Toggle Favorite :white_check_mark:
- Context Menu :white_check_mark:
- Edit/Duplicate/Delete :white_check_mark:
- Sheet Lock :white_check_mark:
- DC / Atk Mod Calculations :white_check_mark:
- Raw Spell Atk Roll :white_check_mark:
- Prepared Spells Tracker :white_check_mark:
- Spellcasting Ability Selector :white_check_mark:

~~Fixing spellbook filter now~~ Fixed.

**Comment by kgar** [comment]
PC Features
- Search :white_check_mark:
- Filter :white_check_mark:
- Expand All / Collapse All :white_check_mark:
- Race (Add/Edit/Delete) :white_check_mark:
- Background (Add/Edit/Delete) :white_check_mark:
- Classes (Add/Edit/Delete) :white_check_mark:
- Subclasses (Add/Edit/Delete) :white_check_mark:
- Levelling Up :white_check_mark:
- Using Features (Breath weapon) :white_check_mark:
- Active Abilities (Add/Edit/Delete/Duplicate) :white_check_mark:
- Passive Abilities (Add/Edit/Delete/Duplicate) :white_check_mark:

**Comment by kgar** [comment]
Community devlog for 3.x upgrade: https://discord.com/channels/1167985253072257115/1202514177382678569

**Comment by kgar** [comment]
Closing this issue as completed.
All quick fixes have been made for minimum viable support for 3.x
All issues have been created for building out the new features.
The beta has been released.
