### ISSUE TITLE
Bug: (dnd5e 3x) Vehicle Sheet - Cargo & Crew - Dragging and Dropping items to cargo causes this error and does not drop the item

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#352]
```
base-sheet.mjs:953 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'system')
    at ActorSheet._onDropSingleItem (base-sheet.mjs:953:21)
    at Tidy5eVehicleSheet._onDropSingleItem (Tidy5eKgarVehicleSheet.ts:332:31)
    at transformFirst (base-sheet.mjs:914:36)
    at createItemData (item.mjs:2421:66)
    at Item5e.createWithContents (item.mjs:2436:39)
    at Tidy5eVehicleSheet._onDropItemCreate (base-sheet.mjs:913:35)
    at Tidy5eVehicleSheet._onDropItem (base-sheet.mjs:874:17)
```

**Comment by kgar** [comment]
Fixed.
