### ISSUE TITLE
Bug: (dnd5e 3x) Vehicle Sheet - Description tab issues

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#353]
When there is a description entered into the description tab, the next time the vehicle is opened, this error occurs:

```
logging.ts:37 tidy5e-sheet | Failed to render svelte tab TypeError: Cannot read properties of null (reading 'addEventListener')
    at Tidy5eVehicleSheet.activateListeners (vehicle-sheet.mjs:270:1)
    at Object.activateFoundryJQueryListeners (Tidy5eKgarVehicleSheet.ts:135:15)
    at activateProseMirrorListeners (VehicleDescriptionTab.svelte:12:14)
    at Object.mount [as m] (VehicleDescriptionTab.svelte:26:15)
    at Object.mount [as m] (RerenderAfterFormSubmission.svelte:2:30)
    at Object.mount [as m] (RerenderAfterFormSubmission.svelte:12:25)
    at mount (RerenderAfterFormSubmission.svelte:11:32)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=4c851f67:291:24)
    at mount_component (chunk-J2VQCU4O.js?v=4c851f67:2134:24)
    at Object.mount [as m] (VehicleDescriptionTab.svelte:28:7)
```

When saving changes to the description tab, this error occurs:

```
VehicleDescriptionTab.svelte:24 Uncaught (in promise) TypeError: dispose is not a function
    at Object.destroy [as d] (VehicleDescriptionTab.svelte:24:36)
    at Object.destroy [as d] (RerenderAfterFormSubmission.svelte:2:30)
    at Object.destroy [as d] (RerenderAfterFormSubmission.svelte:12:25)
    at chunk-J2VQCU4O.js?v=4c851f67:1408:17
    at run (chunk-J2VQCU4O.js?v=4c851f67:30:10)
    at Array.forEach (<anonymous>)
    at run_all (chunk-J2VQCU4O.js?v=4c851f67:36:7)
    at check_outros (chunk-J2VQCU4O.js?v=4c851f67:1389:5)
    at Object.update [as p] (RerenderAfterFormSubmission.svelte:11:32)
    at update (chunk-J2VQCU4O.js?v=4c851f67:1351:32)
```

**Comment by kgar** [comment]
Fixed.
