### ISSUE TITLE
bug: (dnd5e 3x) Tidy/Legacy vehicle sheet - Attempting to add "Equipment" causes error

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#365]
- Bug: Same with the Legacy vehicle sheet - Attempting to add "Equipment" produces this console error:
```
Tidy
commons.js:2572 Uncaught TypeError: Cannot create property 'value' on string 'equipment'
    at setProperty (commons.js:2572:19)
    at _expand (commons.js:2337:9)
    at Object.expandObject (commons.js:2341:12)
    at Object.createItem (foundry-adapter.ts:234:29)
    at HTMLButtonElement.defaultCreateFunction (ItemCreateButton.svelte:14:27)
    at HTMLButtonElement.<anonymous> (ItemCreateButton.svelte:21:19)

Legacy
commons.js:2572 Uncaught (in promise) TypeError: Cannot create property 'value' on string 'equipment'
    at setProperty (commons.js:2572:19)
    at _expand (commons.js:2337:9)
    at Object.expandObject (commons.js:2341:12)
    at InventoryElement._onCreate (inventory.mjs:402:29)
    at InventoryElement._onAction (inventory.mjs:352:21)
```

**Comment by kgar** [comment]
Closing as completed.
