### ISSUE TITLE
cleanup: (dnd5e 3.1.x) Deprecation Resolution

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#531]
There are deprecations to be resolved in 3.1.x.
Ensure they are resolved for all sheets / document types in Tidy.

> [!important]
> All deprecations can be found using a standard search in dnd5e's code base: `since: "DnD5e 3.1"`, swapping the version for your target version.

**Comment by kgar** [comment]
- [ ] ```
commons.js:2070 Error: The value of CONFIG.DND5E.limitedUsePeriods has been changed to an object. The former value can be acccessed from .label.
Deprecated since Version DnD5e 3.1
Backwards-compatible support will be removed in Version DnD5e 3.3
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at Object.toString (config.mjs:3460:19)
    at Array.getLabel (SelectOptions.svelte:19:19)
    at create_each_block (SelectOptions.svelte:42:58)
    at create_fragment (SelectOptions.svelte:41:7)
    at init (chunk-J2VQCU4O.js?v=e1e9eae6:2203:35)
    at new SelectOptions (SelectOptions.svelte:35:35)
    at createProxiedComponent (svelte-hooks.js?v=e1e9eae6:341:9)
    at new ProxyComponent (proxy.js?v=e1e9eae6:242:7)
    at new Proxy<SelectOptions> (proxy.js?v=e1e9eae6:349:11)
```

- [ ] ```
commons.js:2070 Error: The value of CONFIG.DND5E.spellPreparationModes has been changed to an object. The former value can be acccessed from .label.
Deprecated since Version DnD5e 3.1
Backwards-compatible support will be removed in Version DnD5e 3.3
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at Object.toString (config.mjs:3460:19)
    at Array.getLabel (SelectOptions.svelte:19:19)
    at create_each_block (SelectOptions.svelte:42:58)
    at create_fragment (SelectOptions.svelte:41:7)
    at init (chunk-J2VQCU4O.js?v=e1e9eae6:2203:35)
    at new SelectOptions (SelectOptions.svelte:35:35)
    at createProxiedComponent (svelte-hooks.js?v=e1e9eae6:341:9)
    at new ProxyComponent (proxy.js?v=e1e9eae6:242:7)
    at new Proxy<SelectOptions> (proxy.js?v=e1e9eae6:349:11)
```

**Comment by kgar** [comment]
Closing as completed.
