### ISSUE TITLE
bug: Errors in 7.3.0

### ISSUE THREAD

**Issue by kgar** [kgar/foundry-vtt-tidy-5e-sheets#877]
From the community: https://discord.com/channels/1167985253072257115/1319189586072830014

[fvtt-Actor-datty-semor-YUmZSq6NsdZkLNi9.json](https://github.com/user-attachments/files/18205295/fvtt-Actor-datty-semor-YUmZSq6NsdZkLNi9.json)

---

Opened CPR's Thunderous Smite item on an actor and attempted to switch it from the default sheet to Tidy on 7.3. The item and actor sheet immediately closed, and the character sheet for that actor can't be opened. Error I'm seeing is:

```Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'toNearest')
[Detected 1 package: tidy5e-sheet(7.3.0)]
    at Tidy5eCharacterSheet.getData (Tidy5eCharacterSheet.svelte.ts:831:61)
    at async Tidy5eCharacterSheet._renderSheet (Tidy5eCharacterSheet.svelte.ts:1626:11)
    at async Tidy5eCharacterSheet.svelte.ts:1618:13
    at async mutex.ts:26:9```

---

Testing on an SRD hero does not re-produce the issue, even using that specific spell

When swapping on a different pre-existing actor for a spell item, it also did not fail, but did output the error below on change

```logging.ts:79 tidy5e-sheet | An error occurred while invoking the onRender callback for custom content 
{error: TypeError: Cannot read properties of undefined (reading 'matches')
    at DragDrop.bind (http://192…, part: {…}, sheet: Tidy5eItemSheetClassic}
error    @    logging.ts:79
replaceCustomContent    @    CustomContentRendererV2.ts:207
_replaceHTML    @    SvelteApplicationMixin.svelte.ts:199
#render    @    foundry-esm.js:44341
await in #render (async)        
_try    @    foundry-esm.js:6645
(anonymous)    @    foundry-esm.js:6617
add    @    foundry-esm.js:6615
render    @    foundry-esm.js:44291
_onSheetChange    @    foundry.js:11285
await in _onSheetChange (async)        
_onUpdate    @    foundry.js:11039
_onUpdate    @    document.mjs:102
_onUpdate    @    item.mjs:1359
(anonymous)    @    foundry-esm.js:56583
(anonymous)    @    foundry-esm.js:56590
#handleUpdateDocuments    @    foundry-esm.js:56590
await in #handleUpdateDocuments (async)        
_updateDocuments    @    foundry-esm.js:56473
await in _updateDocuments (async)        
update    @    foundry-esm.js:12329
await in update (async)        
updateDocuments    @    foundry-esm.js:11473
update    @    foundry-esm.js:11584
setFlag    @    foundry-esm.js:11824
setFlag    @    flags.mjs:38
_updateObject    @    foundry.js:80806
_onSubmit    @    foundry.js:6665```

**Comment by kgar** [comment]
After some investigation, it appears that a module might be interfering with `prepareHitPoints` on `attributes.mjs`. Awaiting results of culprit hunting.

**Comment by kgar** [comment]
These seem to be related to other modules. I will assist as best I can when I learn more from our mutual users.
